apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-gsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-gsb
  template:
    metadata:
      labels:
        app: bot-gsb
      name: bot-gsb
    spec:
      containers:
        - image: nem2dev/bot-bank:gsb
          imagePullPolicy: Always
          name: bot-gsb
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: bot-gsb-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: bot-gsb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/proxy-connect-timeout: "600s"
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/client-max-body-size: "10m"
  name: ingress
spec:
  ingressClassName: nginx
  rules:
  - host: gsb.pgfun.me
    http:
      paths:
      - backend:
          service:
            name: bot-gsb-service
            port:
              number: 80
        path: "/"
        pathType: Prefix